;;; !!! This configuration is handled by HelloImGui and stores several Ini Files, separated by markers like this:
           ;;;<<<INI_NAME>>>;;;

;;;<<<ImGui_655921752_Default>>>;;;
[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][Macro Client]
Pos=95,123
Size=247,318
Collapsed=0

[Window][Timer Keybind]
Pos=631,215
Size=233,229
Collapsed=0

[Window][Settings]
Pos=350,189
Size=214,249
Collapsed=0

[Window][Image Trigger]
Pos=514,303
Size=334,256
Collapsed=0

[Window][Overlay]
Size=1920,1061
Collapsed=0

[Window][Keybinds]
Pos=622,185
Size=226,300
Collapsed=0

[Docking][Data]

;;;<<<Layout_655921752_Default>>>;;;
;;;<<<HelloImGui_Misc>>>;;;
[Layout]
Name=Default
[StatusBar]
Show=false
ShowFps=true
[Theme]
Name=DarculaDarker
;;;<<<SplitIds>>>;;;
{"gImGuiSplitIDs":{}}
